export { default as overlay } from "../assets/images/overlay.png";
export { default as fan1 } from "../assets/images/Pexels Photo by Baby  Him.png";
export { default as fan2 } from "../assets/images/1001186810 1.png";
export { default as fan3 } from "../assets/images/1001186812 1.png";
export { default as fan4 } from "../assets/images/1001186813 1.png";
export { default as chelseaLogo } from "../assets/images/Pexels Photo by Simon Reza.png";
export { default as whatsapp } from "../assets/images/410201-PD391H-802 1.svg";
export { default as facebook } from "../assets/images/10464408 1.svg";
export { default as stadium } from "../assets/images/view-empty-football-stadium 1.png";
export { default as arsernalIcon } from "../assets/images/image 1.png";
export { default as chelseaIcon } from "../assets/images/Frame 27.png";
export { default as calender } from "../assets/images/Frame 36.png";
export { default as clock } from "../assets/images/Clock.png";
export { default as location } from "../assets/images/Frame 37.png";
export { default as checkMark } from "../assets/images/Vector.svg";
export { default as overlay2 } from "../assets/images/SECTION 2.png";
export { default as football } from "../assets/images/ecb02129-26e7-40fd-8c04-f76de1dfaaa7 1.png";
export { default as chatScreenshot } from "../assets/images/Frame 98.svg";
export { default as image1 } from "../assets/images/image 22.png";
export { default as image2 } from "../assets/images/image 23.svg";
export { default as image3 } from "../assets/images/image 20.png";
export { default as image4} from "../assets/images/image 19.png";
export { default as image5} from "../assets/images/image 21.png";
export { default as image6} from "../assets/images/image 24.png";
export { default as image7} from "../assets/images/image 16.png";
export { default as image8} from "../assets/images/image 15.png";
export { default as image9} from "../assets/images/image 17.png";
export { default as image10} from "../assets/images/image 14.png";
export { default as image11} from "../assets/images/image 13.png";
export { default as iconArrowDown} from "../assets/images/Vector (2).png";
export { default as checkedMark} from "../assets/images/CheckCircle.svg";
export { default as overlay3} from "../assets/images/Frame 2.svg";
